### ISSUE TITLE
Need SOLID refactoring

### ISSUE THREAD

**Issue by progsmile** [progsmile/request-validator#10]
Hello) How to make Validator class - make only it's task? (Just validate)
Should I separate it to classes like ErrorsBag, UserMessagesBag, DbConnector, etc.. or it works - that's ok?))

Have some thoughts about ErrorsBag class, 

so, when user calls method `$validationResult->getMessages();` I would simple delegate it to ErrorsBag

```
// in Validator
public function getMessages($field)
{
    return ErrorsBag::getMessages($field);
}
```

Is it normal ?) Thanks

**Comment by sergeyklay** [comment]
For inspiration https://github.com/Respect/Validation/blob/master/docs/VALIDATORS.md :wink:

**Comment by progsmile** [comment]
@sergeyklay thanks))
