### ISSUE TITLE
We should have our own standard

### ISSUE THREAD

**Issue by daison12006013** [progsmile/request-validator#2]
@progsmile, let's follow the autoloading.

Please don't use 'include' anymore, that is why I already have the test.php file to include the **vendor/autoload.php**

You just need to run **composer dumpautoload** to update your composer classmap and run your command line: **php test.php** the test should work fine.

The Coding style should we follow PSR-1 and PSR-2, there are too much spaces, let's use 4 spaces for function spacing and 1 single space for each functions.

I did a commit on my forked branch, there is a  2 conflicts https://github.com/daison12006013/phalcon-validator.

I modified and added something on test.php and Validator.php

**Comment by progsmile** [comment]
@daison12006013, all right) Just don't know **dumpautoload** command

**Comment by daison12006013** [comment]
@progsmile, there is a composer.json, and vendor/

always run this: **composer dumpautoload** everytime you're change a class

```
vagrant@vagrant:$ composer dumpautoload
vagrant@vagrant:$ php ./test.php
```
