### ISSUE TITLE
accepted  and  required

### ISSUE THREAD

**Issue by ckinmind** [progsmile/request-validator#5]
1. what's the difference between accepted  and  required  ?
2. I found '0' , '  ',  0  will not pass the two validation

**Comment by progsmile** [comment]
@ckinmind, thanks a lot for issue)
1. I thought, rule accepted would be for checkbox or radio fields - will repair it now, and there would be values like (yes, on, 1, or true)
2. Yep, it's bug with '0', but not with ' '
everything is string in request, so 0 equals '0')

**Comment by ckinmind** [comment]
@progsmile, thank for answer
1. I thought the phalcon validation is hard to use , so this is why I use your validator code.
2. On this part (validation) ,laravel is more easy to use
3. I thought the unique validator is a little complex , I just put the DB search in the unique.php , in fact I'm just a php beginner ,so I will always confused with the namespace 
4. thanks for your great job , I wil recommend this to my colleague

**Comment by progsmile** [comment]
@ckinmind I'll fix some issues with image, add some db providers for unique - and pack it to composer)
add new test with required, it works) 
https://github.com/progsmile/request-validator/blob/master/tests/ValidatorTest.php#L121
