### ISSUE TITLE
Composer package settings

### ISSUE THREAD

**Issue by progsmile** [progsmile/request-validator#9]
Hi) How can I simple use 
`composer require progsmile/request-validator`

instead of
`composer require progsmile/request-validator=dev-master` ?
Error message 
`Could not find package progsmile/request-validator at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`
I have `"minimum-stability": "dev"` in `composer.json`, don't understand how it works)

**Comment by sergeyklay** [comment]
Fixed https://github.com/progsmile/request-validator/pull/11
